apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 2                     # this is number of pods
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
      - name: webapp
        image: $(TF_VAR_WS_DOCKERIMAGE)
        imagePullPolicy: Always
        env:
        - name: POSTGRES_DB
          value: $(POSTGRES_DB)
        - name: POSTGRES_USER
          value: $(POSTGRES_USER)
        - name: POSTGRES_PASSWORD
          value: $(POSTGRES_PASSWORD)
        - name: POSTGRES_IP
          value: $(POSTGRES_IP)
        - name: POSTGRES_PORT
          value: $(POSTGRES_PORT)

        resources:
          limits:
            memory: 64Mi
            cpu: "250m"
          requests:
            memory: 32Mi
            cpu: "200m"
        # specify the container port
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: flask-webapp
  ports:
    - name: http
      protocol: TCP
      port: 80             
      targetPort: 5000

    - name: https
      protocol: TCP
      port: 443            
      targetPort: 5000

---

