---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp-$CONFIG
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-webapp-$CONFIG
  template:
    metadata:
      labels:
        app: flask-webapp-$CONFIG
    spec:
      containers:
        - name: webapp
          image: $WS_DOCKERIMAGE
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
            - name: POSTGRES_IP
              value: $POSTGRES_IP
            - name: POSTGRES_PORT
              value: "5432"
          resources:
            limits:
              memory: 1Gi
              cpu: "250m"
            requests:
              memory: 256Mi
              cpu: "200m"
          # specify the container port
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-flask-webapp-$CONFIG
spec:
  type: LoadBalancer
  selector:
    app: flask-webapp-$CONFIG
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
---
