---
apiVersion: v1
kind: Service
metadata:
  name: postgres-$CONFIG
spec:
  ports:
    - port: $POSTGRES_PORT
  selector:
    app: postgres-$CONFIG
  type: LoadBalancer
  loadBalancerIP: $POSTGRES_IP
