---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-$CONFIG
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: postgres-$CONFIG
  template:
    metadata:
      labels:
        app: postgres-$CONFIG
    spec:
      containers:
        - name: postgres-$CONFIG
          image: postgres:11
          resources:
            limits:
              cpu: "250m"
              memory: 64Mi
            requests:
              cpu: "200m"
              memory: 32Mi
          ports:
            - containerPort: $POSTGRES_PORT
          env:
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
            - name: POSTGRES_IP
              value: $POSTGRES_IP
            - name: POSTGRES_PORT
              value: "5432"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-$CONFIG
      volumes:
        - name: postgredb-$CONFIG
          persistentVolumeClaim:
            claimName: postgresql-pv-$CONFIG
